name: Format check

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length=135"
          # src: "./tests"
          version: "~= 22.0"
