name: Run pytest
on:
  push:
    branches:
      - main
jobs:
  pydantic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed py files
        id: changed-py-files
        uses: tj-actions/changed-files@v41
        with:
          path: ./pydantic-service
          files: |
            **.py

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          ls
          cd pydantic-service
          echo "pwd:" $PWD
          python -B -m pytest -v
