name: Run pytest
on:
  push:
    branches:
      - main
jobs:
  pydantic-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run:
          set -x
          cd pydantic-service
          python -B -m pytest -v
